from pydantic import BaseModel, Field
from typing import Literal, List


class SourceDefinition(BaseModel):
    slug: str
    name: str
    url: str
    source_type: str
    actor_alignment: str
    raw_data_available: bool
    access_type: str
    enabled: bool
    ingestion_status: Literal["active", "planned", "manual", "disabled"]
    notes: str | None = None
    reliability_score: int = 0
    propaganda_risk: str = "unknown"
    language_codes: List[str] = Field(default_factory=list)


SOURCE_REGISTRY = [
    SourceDefinition(
        slug="russian-casualties-in-ua",
        name="russian-casualties.in.ua",
        url="https://russian-casualties.in.ua/",
        source_type="osint",
        actor_alignment="independent",
        raw_data_available=False,
        access_type="public",
        enabled=False,
        ingestion_status="planned",
        notes="Planned public inventory source; ingestion requires careful attribution checks.",
        reliability_score=40,
        propaganda_risk="medium",
        language_codes=["en", "uk"],
    ),
    SourceDefinition(
        slug="isw",
        name="Institute for the Study of War",
        url="https://www.understandingwar.org/",
        source_type="analysis",
        actor_alignment="independent",
        raw_data_available=False,
        access_type="public",
        enabled=False,
        ingestion_status="planned",
        notes="Open reporting and analysis; source connector scaffolded.",
        reliability_score=70,
        propaganda_risk="low",
        language_codes=["en"],
    ),
    SourceDefinition(
        slug="acled-ukraine-conflict-monitor",
        name="ACLED Ukraine Conflict Monitor",
        url="https://acleddata.com/",
        source_type="dataset",
        actor_alignment="independent",
        raw_data_available=False,
        access_type="public",
        enabled=False,
        ingestion_status="planned",
        notes="ACLED provides conflict datasets; use public dataset exports for ingestion.",
        reliability_score=65,
        propaganda_risk="low",
        language_codes=["en"],
    ),
    SourceDefinition(
        slug="liveuamap",
        name="LiveUAmap",
        url="https://liveuamap.com/",
        source_type="map",
        actor_alignment="independent",
        raw_data_available=False,
        access_type="public",
        enabled=False,
        ingestion_status="manual",
        notes="Manual ingestion is preferred; scraping dynamic web content is not implemented.",
        reliability_score=50,
        propaganda_risk="medium",
        language_codes=["en", "uk"],
    ),
    SourceDefinition(
        slug="viina",
        name="VIINA",
        url="https://viina.info/",
        source_type="media",
        actor_alignment="independent",
        raw_data_available=False,
        access_type="public",
        enabled=False,
        ingestion_status="planned",
        notes="Planned open-source reporting registry.",
        reliability_score=45,
        propaganda_risk="medium",
        language_codes=["en", "uk"],
    ),
    SourceDefinition(
        slug="oryx",
        name="Oryx",
        url="https://www.oryxspioenkop.com/",
        source_type="osint",
        actor_alignment="independent",
        raw_data_available=False,
        access_type="public",
        enabled=False,
        ingestion_status="planned",
        notes="Open equipment loss tracker; ingestion is planned.",
        reliability_score=55,
        propaganda_risk="medium",
        language_codes=["en"],
    ),
    SourceDefinition(
        slug="ukrdailyupdate",
        name="ukrdailyupdate / Andrew Perpetua",
        url="https://ukrdailyupdate.substack.com/",
        source_type="media",
        actor_alignment="independent",
        raw_data_available=False,
        access_type="public",
        enabled=False,
        ingestion_status="manual",
        notes="News summary site; manual monitoring is recommended.",
        reliability_score=45,
        propaganda_risk="medium",
        language_codes=["en"],
    ),
    SourceDefinition(
        slug="ukraine-general-staff",
        name="Ukrainian General Staff",
        url="https://www.facebook.com/GeneralStaff.ua",
        source_type="official_military",
        actor_alignment="ukraine",
        raw_data_available=False,
        access_type="manual",
        enabled=False,
        ingestion_status="manual",
        notes="Official claims require careful attribution and review.",
        reliability_score=60,
        propaganda_risk="medium",
        language_codes=["uk"],
    ),
    SourceDefinition(
        slug="russian-mod",
        name="Russian Ministry of Defence",
        url="https://eng.mil.ru/",
        source_type="official_military",
        actor_alignment="russia",
        raw_data_available=False,
        access_type="manual",
        enabled=False,
        ingestion_status="manual",
        notes="Official claims require caution and confirmation.",
        reliability_score=35,
        propaganda_risk="high",
        language_codes=["ru"],
    ),
    SourceDefinition(
        slug="osw-arms-deliveries",
        name="OSW Arms Deliveries",
        url="https://www.osw.waw.pl/",
        source_type="analysis",
        actor_alignment="independent",
        raw_data_available=False,
        access_type="public",
        enabled=False,
        ingestion_status="planned",
        notes="Open analysis of arms transfers; ingestion remains planned.",
        reliability_score=60,
        propaganda_risk="low",
        language_codes=["en"],
    ),
    SourceDefinition(
        slug="kaggle-missile-attacks",
        name="Kaggle missile attacks dataset",
        url="https://www.kaggle.com/",
        source_type="dataset",
        actor_alignment="independent",
        raw_data_available=False,
        access_type="manual",
        enabled=False,
        ingestion_status="planned",
        notes="Public datasets are planned for offline ingestion only.",
        reliability_score=50,
        propaganda_risk="unknown",
        language_codes=["en"],
    ),
    SourceDefinition(
        slug="nasa-firms",
        name="NASA FIRMS",
        url="https://earthdata.nasa.gov/",
        source_type="dataset",
        actor_alignment="independent",
        raw_data_available=False,
        access_type="public",
        enabled=False,
        ingestion_status="planned",
        notes="Scientific thermal anomaly data is planned for geospatial analysis.",
        reliability_score=70,
        propaganda_risk="low",
        language_codes=["en"],
    ),
    SourceDefinition(
        slug="reliefweb-hdx",
        name="ReliefWeb / HDX",
        url="https://data.humdata.org/",
        source_type="dataset",
        actor_alignment="international",
        raw_data_available=False,
        access_type="public",
        enabled=False,
        ingestion_status="planned",
        notes="Humanitarian and crisis data sources are planned.",
        reliability_score=65,
        propaganda_risk="low",
        language_codes=["en"],
    ),
]
